### PR TITLE
[i18n] Occitan localisation file

### PR DESCRIPTION
**Pull request by Quenty31**
I hope it's okay that way!
It's not 100% translated but I'm working on it!

### CODE REVIEW

**Comment by ghost** [comment]
Nice @Quenty31 :) Thank you.

**Review by ghost — APPROVED** [review]

**Comment by syuilo** [comment]
Even if those files are changed, they are not reflected in Crowdin. So I close this PR and import the file.
Thank you🥰

**Comment by Quenty31** [comment]
Thank you :)
I'm looking forward to seeing it in next release!

**Comment by syuilo** [comment]
👍 
image

**Comment by ghost** [comment]
Thank you @syuilo \o/

**Pull request closed without merging**
